[package]
name = "black-mesa"
version = "0.3.4"
edition = "2021"

[dependencies]
twilight-cache-inmemory = "0.13"
twilight-command-parser = "0.9"
twilight-embed-builder = "0.11"
twilight-gateway = "0.13"
twilight-gateway-queue = "0.13"
twilight-http = "0.13"
twilight-mention = "0.13"
twilight-model = "0.13"
twilight-util = { version = "0.13", features = ["builder"] }
tokio = { version = "1.21", features = ["full"] }
mongodb = { version = "2.3", features = ["tokio-runtime"] }
serde = { version = "1.0" }
serde_derive = "1.0"
serde_json = "1.0"
serde-aux = "4.0"
serde_with = "2.0"
regex = "1.6"
lazy_static = "1.4"
built = "0.5"
bson = "2.4"
strum = "0.24"
strum_macros = "0.24"
futures = "0.3"
futures-util = "0.3"
chrono = "0.4"
cached = "0.39"
self-meter = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.redis]
version = "*"
features = ["tokio-comp"]

[dependencies.uuid]
version = "1.2"
features = [
    "v4",
    "fast-rng",
]