[package]
name = "black-mesa"
version = "0.4.0"
edition = "2021"

[dependencies]
twilight-cache-inmemory = "0.15"
twilight-command-parser = "0.9"
twilight-embed-builder = "0.11"
twilight-gateway = "0.15"
twilight-gateway-queue = "0.15"
twilight-http = "0.15"
twilight-mention = "0.15"
twilight-model = "0.15"
twilight-util = { version = "0.15", features = ["builder"] }
tokio = { version = "1.32", features = ["full"] }
mongodb = { version = "2.6", features = ["tokio-runtime"] }
redis = { version = "*", features = ["tokio-comp"] }
serde = { version = "1.0" }
uuid = { version = "1.4", features = ["v4", "fast-rng"] }
axum = "0.6"
serde_derive = "1.0"
serde_json = "1.0"
serde-aux = "4.2"
serde_with = "3.3"
regex = "1.9"
lazy_static = "1.4"
bson = "2.6"
strum = "0.25"
strum_macros = "0.25"
futures = "0.3"
futures-util = "0.3"
chrono = "0.4"
cached = "0.46"
self-meter = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-axiom = "0.4"
serde_yaml = "0.9"
axum-yaml = "0.3"

tesseract = { version = "0.15.0", optional = true }

[features]
tesseract = ["dep:tesseract"]