site_name: Black Mesa
site_description: >-
  Moderation for the server owner who loves configuration.

repo_name: blackmesadev/black-mesa
repo_url: https://github.com/blackmesadev/black-mesa

theme:
  name: material
  logo: assets/monogram.svg
  favicon: assets/monogram.png

  palette:
    scheme: slate
    primary: black

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2021 Tyler#0911 & LewisTehMinerz#1337

extra:
  social:
    - icon: fontawesome/brands/discord
      link: http://test

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true


plugins:
  - search
  - minify:
      minify_html: true