site_name: Black Mesa
site_description: >-
  Moderation for the server owner who loves configuration.

repo_name: trollrocks/black-mesa
repo_url: https://github.com/trollrocks/black-mesa

theme:
  name: material
  logo: assets/monogram.svg
  favicon: assets/monogram.png

  palette:
    scheme: slate
    accent: orange

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2021 Black Mesa Development

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ZezqXEXBDJ

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search
  - minify:
      minify_html: true